"""Initial schema with research IDs

Revision ID: 39bc126e2b3a
Revises: 
Create Date: 2025-11-01 09:50:52.276598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39bc126e2b3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paco_research_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paco_research_ids_id'), 'paco_research_ids', ['id'], unique=False)
    op.create_index(op.f('ix_paco_research_ids_research_id'), 'paco_research_ids', ['research_id'], unique=True)
    op.create_table('paco_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_id_fk', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['research_id_fk'], ['paco_research_ids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_research_timestamp', 'paco_conversations', ['conversation_id', 'timestamp'], unique=False)
    op.create_index('ix_research_timestamp', 'paco_conversations', ['research_id_fk', 'timestamp'], unique=False)
    op.create_index(op.f('ix_paco_conversations_conversation_id'), 'paco_conversations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_paco_conversations_id'), 'paco_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_paco_conversations_timestamp'), 'paco_conversations', ['timestamp'], unique=False)
    op.create_table('paco_disclaimer_acknowledgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_id_fk', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('disclaimer_version', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['research_id_fk'], ['paco_research_ids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paco_disclaimer_acknowledgments_id'), 'paco_disclaimer_acknowledgments', ['id'], unique=False)
    op.create_table('paco_user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_id_fk', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['research_id_fk'], ['paco_research_ids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paco_user_sessions_id'), 'paco_user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_paco_user_sessions_session_token'), 'paco_user_sessions', ['session_token'], unique=True)
    
    # Drop old conversations table if it exists (for migration from older schema)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    if 'conversations' in inspector.get_table_names():
        op.drop_table('conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey')
    )
    op.drop_index(op.f('ix_paco_user_sessions_session_token'), table_name='paco_user_sessions')
    op.drop_index(op.f('ix_paco_user_sessions_id'), table_name='paco_user_sessions')
    op.drop_table('paco_user_sessions')
    op.drop_index(op.f('ix_paco_disclaimer_acknowledgments_id'), table_name='paco_disclaimer_acknowledgments')
    op.drop_table('paco_disclaimer_acknowledgments')
    op.drop_index(op.f('ix_paco_conversations_timestamp'), table_name='paco_conversations')
    op.drop_index(op.f('ix_paco_conversations_id'), table_name='paco_conversations')
    op.drop_index(op.f('ix_paco_conversations_conversation_id'), table_name='paco_conversations')
    op.drop_index('ix_research_timestamp', table_name='paco_conversations')
    op.drop_index('ix_conversation_research_timestamp', table_name='paco_conversations')
    op.drop_table('paco_conversations')
    op.drop_index(op.f('ix_paco_research_ids_research_id'), table_name='paco_research_ids')
    op.drop_index(op.f('ix_paco_research_ids_id'), table_name='paco_research_ids')
    op.drop_table('paco_research_ids')
    # ### end Alembic commands ###
